name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  alert: ^2.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  fluttertoast: ^9.0.0
  http: ^1.4.0
  intl: ^0.20.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  toast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
